from .errors.dat_exception import DatException